packer {
  required_version = ">= 1.6.5"
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command              = ["<esc><wait>", "<esc><wait>", "<enter><wait>", "/install/vmlinuz", " auto=true", " fb=false", " initrd=/install/initrd.gz", " netcfg/get_domain=${var.domain}", " netcfg/get_hostname=${var.hostname}", " grub-installer/bootdev=/dev/sda", " noapic", " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg", " -- <enter>"]
  boot_wait                 = "10s"
  cpus                      = 2
  disk_size                 = 61440
  format                    = "ova"
  guest_additions_mode      = "disable"
  guest_os_type             = "Ubuntu_64"
  headless                  = false
  http_directory            = "."
  iso_checksum              = "sha256:8c5fc24894394035402f66f3824beb7234b757dd2b5531379cb310cedfdf0996"
  iso_url                   = "http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/ubuntu-18.04.5-server-amd64.iso"
  memory                    = 4096
  shutdown_command          = "echo ${var.ubuntu_password} | sudo -S shutdown -P now"
  ssh_clear_authorized_keys = true
  ssh_password              = "${var.ubuntu_password}"
  ssh_port                  = 22
  ssh_timeout               = "1800s"
  ssh_username              = "ubuntu"
  vm_name                   = "${var.hostname}"
}

build {
  description = "packer ubuntu18 CIS-conformant base image with a 60Gb disk"

  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["GMAIL=${var.email}"]
    execute_command  = "echo '${var.ubuntu_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    script           = "baseInit.sh"
  }

  provisioner "shell" {
    environment_vars = ["GRUB_PASSWORD=${var.grubPassword}", "GMAIL=${var.email}", "GMAILPASSWORD=${var.emailPassword}", "REMOTELOGHOST=${var.remoteLogHost}", "HOSTNAME=${var.hostname}", "DOMAIN=${var.domain}"]
    execute_command  = "echo '${var.ubuntu_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    script           = "cis.sh"
  }

  provisioner "shell" {
    environment_vars = ["GMAIL=${var.email}", "GMAILPASSWORD=${var.emailPassword}"]
    execute_command  = "echo '${var.ubuntu_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    script           = "baseClean.sh"
  }

  provisioner "file" {
    destination = "/tmp/installHC.sh"
    source      = "installHC.sh"
  }

  provisioner "shell" {
    execute_command = "echo '${var.ubuntu_password}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    inline          = ["mv -f /tmp/installHC.sh /usr/local/bin"]
  }

  post-processor "vagrant" {
    compression_level = 8
    output            = "u18.box"
  }
  post-processor "amazon-import" {
    access_key      = "${var.aws_access_key_id}"
    ami_description = "Reduced, minimal Ubuntu 18 image with CIS compliance added."
    ami_name        = "base"
    region          = "${var.region}"
    s3_bucket_name  = "${var.s3_bucket}"
    secret_key      = "${var.aws_secret_access_key}"
    tags = {
      Name = "${var.hostname}"
    }
    token = "${var.aws_session_token}"
  }
}
